services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: wex-transaction
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
